version: '3'

services:
  todoback:
    image: todobackend
    ports:
      - 3001:3001
    networks:
      - todo-app
    restart: always
  todofront:
    image: todofrontend
    environment:
      - REACT_APP_API_HOST=todoback
      - REACT_APP_API_PORT=3001
    ports:
      - 3000:3000
    networks:
      - todo-app
    depends_on:
      - todoback
    restart: always
  todotests:
    image: todotests
    environment:
      - FRONT_HOST=todofront
      - FRONT_PORT=3000
    networks:
      - todo-app
    restart: always
    depends_on:
      - todoback
      - todofront

networks:
  todo-app: